# Generated by Django 4.0.3 on 2022-03-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cerrajero',
            fields=[
                ('profesional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profesionales.profesional')),
                ('desempleado', models.BooleanField()),
                ('tel', models.IntegerField()),
            ],
            bases=('profesionales.profesional',),
        ),
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('profesional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profesionales.profesional')),
                ('club_futbol', models.CharField(max_length=30)),
            ],
            bases=('profesionales.profesional',),
        ),
    ]
